-- Generated by scripts/generate-supabase-permissions.ts. Do not edit by hand.
-- Regenerate with: npm run db:permissions:generate
--
-- Supabase Data API hardening:
-- - every public-schema Prisma table gets explicit grants
-- - RLS is enabled on every table
-- - public content allows anon SELECT only
-- - ERP/business tables deny anon and authenticated row access until a scoped policy exists

begin;

revoke all on schema "public" from public;
grant usage on schema "public" to anon, authenticated, service_role;

-- User: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."User" from public;
revoke all on table "public"."User" from anon;
revoke all on table "public"."User" from authenticated;
grant select, insert, update, delete on table "public"."User" to authenticated;
grant select, insert, update, delete on table "public"."User" to service_role;
alter table "public"."User" enable row level security;
drop policy if exists "service_role_all_user" on "public"."User";
create policy "service_role_all_user"
on "public"."User"
as permissive
for all
to service_role
using (true)
with check (true);

-- Role: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."Role" from public;
revoke all on table "public"."Role" from anon;
revoke all on table "public"."Role" from authenticated;
grant select, insert, update, delete on table "public"."Role" to authenticated;
grant select, insert, update, delete on table "public"."Role" to service_role;
alter table "public"."Role" enable row level security;
drop policy if exists "service_role_all_role" on "public"."Role";
create policy "service_role_all_role"
on "public"."Role"
as permissive
for all
to service_role
using (true)
with check (true);

-- RolePermission: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."RolePermission" from public;
revoke all on table "public"."RolePermission" from anon;
revoke all on table "public"."RolePermission" from authenticated;
grant select, insert, update, delete on table "public"."RolePermission" to authenticated;
grant select, insert, update, delete on table "public"."RolePermission" to service_role;
alter table "public"."RolePermission" enable row level security;
drop policy if exists "service_role_all_role_permission" on "public"."RolePermission";
create policy "service_role_all_role_permission"
on "public"."RolePermission"
as permissive
for all
to service_role
using (true)
with check (true);

-- UserPermission: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."UserPermission" from public;
revoke all on table "public"."UserPermission" from anon;
revoke all on table "public"."UserPermission" from authenticated;
grant select, insert, update, delete on table "public"."UserPermission" to authenticated;
grant select, insert, update, delete on table "public"."UserPermission" to service_role;
alter table "public"."UserPermission" enable row level security;
drop policy if exists "service_role_all_user_permission" on "public"."UserPermission";
create policy "service_role_all_user_permission"
on "public"."UserPermission"
as permissive
for all
to service_role
using (true)
with check (true);

-- Client: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."Client" from public;
revoke all on table "public"."Client" from anon;
revoke all on table "public"."Client" from authenticated;
grant select, insert, update, delete on table "public"."Client" to authenticated;
grant select, insert, update, delete on table "public"."Client" to service_role;
alter table "public"."Client" enable row level security;
drop policy if exists "service_role_all_client" on "public"."Client";
create policy "service_role_all_client"
on "public"."Client"
as permissive
for all
to service_role
using (true)
with check (true);

-- Supplier: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."Supplier" from public;
revoke all on table "public"."Supplier" from anon;
revoke all on table "public"."Supplier" from authenticated;
grant select, insert, update, delete on table "public"."Supplier" to authenticated;
grant select, insert, update, delete on table "public"."Supplier" to service_role;
alter table "public"."Supplier" enable row level security;
drop policy if exists "service_role_all_supplier" on "public"."Supplier";
create policy "service_role_all_supplier"
on "public"."Supplier"
as permissive
for all
to service_role
using (true)
with check (true);

-- Lead: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."Lead" from public;
revoke all on table "public"."Lead" from anon;
revoke all on table "public"."Lead" from authenticated;
grant select, insert, update, delete on table "public"."Lead" to authenticated;
grant select, insert, update, delete on table "public"."Lead" to service_role;
alter table "public"."Lead" enable row level security;
drop policy if exists "service_role_all_lead" on "public"."Lead";
create policy "service_role_all_lead"
on "public"."Lead"
as permissive
for all
to service_role
using (true)
with check (true);

-- QuoteRequest: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."QuoteRequest" from public;
revoke all on table "public"."QuoteRequest" from anon;
revoke all on table "public"."QuoteRequest" from authenticated;
grant select, insert, update, delete on table "public"."QuoteRequest" to authenticated;
grant select, insert, update, delete on table "public"."QuoteRequest" to service_role;
alter table "public"."QuoteRequest" enable row level security;
drop policy if exists "service_role_all_quote_request" on "public"."QuoteRequest";
create policy "service_role_all_quote_request"
on "public"."QuoteRequest"
as permissive
for all
to service_role
using (true)
with check (true);

-- Material: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."Material" from public;
revoke all on table "public"."Material" from anon;
revoke all on table "public"."Material" from authenticated;
grant select, insert, update, delete on table "public"."Material" to authenticated;
grant select, insert, update, delete on table "public"."Material" to service_role;
alter table "public"."Material" enable row level security;
drop policy if exists "service_role_all_material" on "public"."Material";
create policy "service_role_all_material"
on "public"."Material"
as permissive
for all
to service_role
using (true)
with check (true);

-- Stok: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."Stok" from public;
revoke all on table "public"."Stok" from anon;
revoke all on table "public"."Stok" from authenticated;
grant select, insert, update, delete on table "public"."Stok" to authenticated;
grant select, insert, update, delete on table "public"."Stok" to service_role;
alter table "public"."Stok" enable row level security;
drop policy if exists "service_role_all_stok" on "public"."Stok";
create policy "service_role_all_stok"
on "public"."Stok"
as permissive
for all
to service_role
using (true)
with check (true);

-- StokArtikull: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."StokArtikull" from public;
revoke all on table "public"."StokArtikull" from anon;
revoke all on table "public"."StokArtikull" from authenticated;
grant select, insert, update, delete on table "public"."StokArtikull" to authenticated;
grant select, insert, update, delete on table "public"."StokArtikull" to service_role;
alter table "public"."StokArtikull" enable row level security;
drop policy if exists "service_role_all_stok_artikull" on "public"."StokArtikull";
create policy "service_role_all_stok_artikull"
on "public"."StokArtikull"
as permissive
for all
to service_role
using (true)
with check (true);

-- AssetInventory: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."AssetInventory" from public;
revoke all on table "public"."AssetInventory" from anon;
revoke all on table "public"."AssetInventory" from authenticated;
grant select, insert, update, delete on table "public"."AssetInventory" to authenticated;
grant select, insert, update, delete on table "public"."AssetInventory" to service_role;
alter table "public"."AssetInventory" enable row level security;
drop policy if exists "service_role_all_asset_inventory" on "public"."AssetInventory";
create policy "service_role_all_asset_inventory"
on "public"."AssetInventory"
as permissive
for all
to service_role
using (true)
with check (true);

-- Product: public-facing content. Anon/authenticated Data API clients may read only.
revoke all on table "public"."Product" from public;
revoke all on table "public"."Product" from anon;
revoke all on table "public"."Product" from authenticated;
grant select on table "public"."Product" to anon;
grant select, insert, update, delete on table "public"."Product" to authenticated;
grant select, insert, update, delete on table "public"."Product" to service_role;
alter table "public"."Product" enable row level security;
drop policy if exists "anon_select_public_product" on "public"."Product";
create policy "anon_select_public_product"
on "public"."Product"
as permissive
for select
to anon
using (true);
drop policy if exists "authenticated_select_public_product" on "public"."Product";
create policy "authenticated_select_public_product"
on "public"."Product"
as permissive
for select
to authenticated
using (true);
drop policy if exists "service_role_all_product" on "public"."Product";
create policy "service_role_all_product"
on "public"."Product"
as permissive
for all
to service_role
using (true)
with check (true);

-- ProductBomItem: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."ProductBomItem" from public;
revoke all on table "public"."ProductBomItem" from anon;
revoke all on table "public"."ProductBomItem" from authenticated;
grant select, insert, update, delete on table "public"."ProductBomItem" to authenticated;
grant select, insert, update, delete on table "public"."ProductBomItem" to service_role;
alter table "public"."ProductBomItem" enable row level security;
drop policy if exists "service_role_all_product_bom_item" on "public"."ProductBomItem";
create policy "service_role_all_product_bom_item"
on "public"."ProductBomItem"
as permissive
for all
to service_role
using (true)
with check (true);

-- Offer: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."Offer" from public;
revoke all on table "public"."Offer" from anon;
revoke all on table "public"."Offer" from authenticated;
grant select, insert, update, delete on table "public"."Offer" to authenticated;
grant select, insert, update, delete on table "public"."Offer" to service_role;
alter table "public"."Offer" enable row level security;
drop policy if exists "service_role_all_offer" on "public"."Offer";
create policy "service_role_all_offer"
on "public"."Offer"
as permissive
for all
to service_role
using (true)
with check (true);

-- OfferItem: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."OfferItem" from public;
revoke all on table "public"."OfferItem" from anon;
revoke all on table "public"."OfferItem" from authenticated;
grant select, insert, update, delete on table "public"."OfferItem" to authenticated;
grant select, insert, update, delete on table "public"."OfferItem" to service_role;
alter table "public"."OfferItem" enable row level security;
drop policy if exists "service_role_all_offer_item" on "public"."OfferItem";
create policy "service_role_all_offer_item"
on "public"."OfferItem"
as permissive
for all
to service_role
using (true)
with check (true);

-- Invoice: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."Invoice" from public;
revoke all on table "public"."Invoice" from anon;
revoke all on table "public"."Invoice" from authenticated;
grant select, insert, update, delete on table "public"."Invoice" to authenticated;
grant select, insert, update, delete on table "public"."Invoice" to service_role;
alter table "public"."Invoice" enable row level security;
drop policy if exists "service_role_all_invoice" on "public"."Invoice";
create policy "service_role_all_invoice"
on "public"."Invoice"
as permissive
for all
to service_role
using (true)
with check (true);

-- InvoiceItem: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."InvoiceItem" from public;
revoke all on table "public"."InvoiceItem" from anon;
revoke all on table "public"."InvoiceItem" from authenticated;
grant select, insert, update, delete on table "public"."InvoiceItem" to authenticated;
grant select, insert, update, delete on table "public"."InvoiceItem" to service_role;
alter table "public"."InvoiceItem" enable row level security;
drop policy if exists "service_role_all_invoice_item" on "public"."InvoiceItem";
create policy "service_role_all_invoice_item"
on "public"."InvoiceItem"
as permissive
for all
to service_role
using (true)
with check (true);

-- PurchaseInvoice: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."PurchaseInvoice" from public;
revoke all on table "public"."PurchaseInvoice" from anon;
revoke all on table "public"."PurchaseInvoice" from authenticated;
grant select, insert, update, delete on table "public"."PurchaseInvoice" to authenticated;
grant select, insert, update, delete on table "public"."PurchaseInvoice" to service_role;
alter table "public"."PurchaseInvoice" enable row level security;
drop policy if exists "service_role_all_purchase_invoice" on "public"."PurchaseInvoice";
create policy "service_role_all_purchase_invoice"
on "public"."PurchaseInvoice"
as permissive
for all
to service_role
using (true)
with check (true);

-- PurchaseInvoiceItem: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."PurchaseInvoiceItem" from public;
revoke all on table "public"."PurchaseInvoiceItem" from anon;
revoke all on table "public"."PurchaseInvoiceItem" from authenticated;
grant select, insert, update, delete on table "public"."PurchaseInvoiceItem" to authenticated;
grant select, insert, update, delete on table "public"."PurchaseInvoiceItem" to service_role;
alter table "public"."PurchaseInvoiceItem" enable row level security;
drop policy if exists "service_role_all_purchase_invoice_item" on "public"."PurchaseInvoiceItem";
create policy "service_role_all_purchase_invoice_item"
on "public"."PurchaseInvoiceItem"
as permissive
for all
to service_role
using (true)
with check (true);

-- DeliveryNote: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."DeliveryNote" from public;
revoke all on table "public"."DeliveryNote" from anon;
revoke all on table "public"."DeliveryNote" from authenticated;
grant select, insert, update, delete on table "public"."DeliveryNote" to authenticated;
grant select, insert, update, delete on table "public"."DeliveryNote" to service_role;
alter table "public"."DeliveryNote" enable row level security;
drop policy if exists "service_role_all_delivery_note" on "public"."DeliveryNote";
create policy "service_role_all_delivery_note"
on "public"."DeliveryNote"
as permissive
for all
to service_role
using (true)
with check (true);

-- DeliveryNoteItem: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."DeliveryNoteItem" from public;
revoke all on table "public"."DeliveryNoteItem" from anon;
revoke all on table "public"."DeliveryNoteItem" from authenticated;
grant select, insert, update, delete on table "public"."DeliveryNoteItem" to authenticated;
grant select, insert, update, delete on table "public"."DeliveryNoteItem" to service_role;
alter table "public"."DeliveryNoteItem" enable row level security;
drop policy if exists "service_role_all_delivery_note_item" on "public"."DeliveryNoteItem";
create policy "service_role_all_delivery_note_item"
on "public"."DeliveryNoteItem"
as permissive
for all
to service_role
using (true)
with check (true);

-- Expense: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."Expense" from public;
revoke all on table "public"."Expense" from anon;
revoke all on table "public"."Expense" from authenticated;
grant select, insert, update, delete on table "public"."Expense" to authenticated;
grant select, insert, update, delete on table "public"."Expense" to service_role;
alter table "public"."Expense" enable row level security;
drop policy if exists "service_role_all_expense" on "public"."Expense";
create policy "service_role_all_expense"
on "public"."Expense"
as permissive
for all
to service_role
using (true)
with check (true);

-- DebitNote: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."DebitNote" from public;
revoke all on table "public"."DebitNote" from anon;
revoke all on table "public"."DebitNote" from authenticated;
grant select, insert, update, delete on table "public"."DebitNote" to authenticated;
grant select, insert, update, delete on table "public"."DebitNote" to service_role;
alter table "public"."DebitNote" enable row level security;
drop policy if exists "service_role_all_debit_note" on "public"."DebitNote";
create policy "service_role_all_debit_note"
on "public"."DebitNote"
as permissive
for all
to service_role
using (true)
with check (true);

-- DebitNoteItem: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."DebitNoteItem" from public;
revoke all on table "public"."DebitNoteItem" from anon;
revoke all on table "public"."DebitNoteItem" from authenticated;
grant select, insert, update, delete on table "public"."DebitNoteItem" to authenticated;
grant select, insert, update, delete on table "public"."DebitNoteItem" to service_role;
alter table "public"."DebitNoteItem" enable row level security;
drop policy if exists "service_role_all_debit_note_item" on "public"."DebitNoteItem";
create policy "service_role_all_debit_note_item"
on "public"."DebitNoteItem"
as permissive
for all
to service_role
using (true)
with check (true);

-- InventoryMovement: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."InventoryMovement" from public;
revoke all on table "public"."InventoryMovement" from anon;
revoke all on table "public"."InventoryMovement" from authenticated;
grant select, insert, update, delete on table "public"."InventoryMovement" to authenticated;
grant select, insert, update, delete on table "public"."InventoryMovement" to service_role;
alter table "public"."InventoryMovement" enable row level security;
drop policy if exists "service_role_all_inventory_movement" on "public"."InventoryMovement";
create policy "service_role_all_inventory_movement"
on "public"."InventoryMovement"
as permissive
for all
to service_role
using (true)
with check (true);

-- Notification: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."Notification" from public;
revoke all on table "public"."Notification" from anon;
revoke all on table "public"."Notification" from authenticated;
grant select, insert, update, delete on table "public"."Notification" to authenticated;
grant select, insert, update, delete on table "public"."Notification" to service_role;
alter table "public"."Notification" enable row level security;
drop policy if exists "service_role_all_notification" on "public"."Notification";
create policy "service_role_all_notification"
on "public"."Notification"
as permissive
for all
to service_role
using (true)
with check (true);

-- Worker: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."Worker" from public;
revoke all on table "public"."Worker" from anon;
revoke all on table "public"."Worker" from authenticated;
grant select, insert, update, delete on table "public"."Worker" to authenticated;
grant select, insert, update, delete on table "public"."Worker" to service_role;
alter table "public"."Worker" enable row level security;
drop policy if exists "service_role_all_worker" on "public"."Worker";
create policy "service_role_all_worker"
on "public"."Worker"
as permissive
for all
to service_role
using (true)
with check (true);

-- WorkerTimeEntry: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."WorkerTimeEntry" from public;
revoke all on table "public"."WorkerTimeEntry" from anon;
revoke all on table "public"."WorkerTimeEntry" from authenticated;
grant select, insert, update, delete on table "public"."WorkerTimeEntry" to authenticated;
grant select, insert, update, delete on table "public"."WorkerTimeEntry" to service_role;
alter table "public"."WorkerTimeEntry" enable row level security;
drop policy if exists "service_role_all_worker_time_entry" on "public"."WorkerTimeEntry";
create policy "service_role_all_worker_time_entry"
on "public"."WorkerTimeEntry"
as permissive
for all
to service_role
using (true)
with check (true);

-- WorkerAdvance: ERP/business data. No anon Data API access; authenticated is denied by RLS until row-scoped policies are added.
revoke all on table "public"."WorkerAdvance" from public;
revoke all on table "public"."WorkerAdvance" from anon;
revoke all on table "public"."WorkerAdvance" from authenticated;
grant select, insert, update, delete on table "public"."WorkerAdvance" to authenticated;
grant select, insert, update, delete on table "public"."WorkerAdvance" to service_role;
alter table "public"."WorkerAdvance" enable row level security;
drop policy if exists "service_role_all_worker_advance" on "public"."WorkerAdvance";
create policy "service_role_all_worker_advance"
on "public"."WorkerAdvance"
as permissive
for all
to service_role
using (true)
with check (true);

commit;
